---
esphome:
  name: kiosk-1
  friendly_name: kiosk-1
  on_boot:
    priority: 0
    then:
      - display.page.show: paint_red
      - component.update: epaper_display
      - display.page.show: paint_white
      - component.update: epaper_display
      - display.page.show: clear
      - component.update: epaper_display
      - display.page.show: content
      - component.update: epaper_display

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "0hSHjfJRSKDKWsi4xeU42qwuyWtKcf+IllX90Tzfsh8="

ota:
  - platform: esphome
    password: "ae914fc7bfa12b4fd5a49395a6bfee56"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Kiosk-1 Fallback Hotspot"
    password: "z8VbVEO3CHSV"

captive_portal:

external_components:
  - source: github://pr#6209
    components: [waveshare_epaper]

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

font:
  - file: "gfonts://Geist Mono"
    id: main_big
    size: 40

time:
  - platform: homeassistant
    id: esptime

display:
  - platform: waveshare_epaper
    id: epaper_display
    cs_pin: GPIO5
    dc_pin: GPIO17
    reset_pin:
      number: GPIO16
      inverted: False
    busy_pin:
      number: GPIO4
      inverted: False
    model: 4.20in-bv2-bwr
    rotation: 180
    update_interval: never
    reset_duration: 2ms
    pages:
      - id: paint_red
        lambda: |-
          it.filled_rectangle(0, 0, it.get_width(), it.get_height(), Color(255, 0, 0));
      - id: paint_white
        lambda: |-
          it.filled_rectangle(0, 0, it.get_width(), it.get_height(), COLOR_OFF);
      - id: clear
        lambda: |-
          it.clear();
      - id: content
        lambda: |-
          it.filled_rectangle(0, 0, it.get_width(), it.get_height(), COLOR_OFF);
          it.print(200, 150, id(main_big), COLOR_ON, TextAlign::CENTER, "Hello World");
