esphome:
  name: kiosk-1
  friendly_name: kiosk-1
  on_boot:
    priority: 200
    then:
      - component.update: epaper_display

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "0hSHjfJRSKDKWsi4xeU42qwuyWtKcf+IllX90Tzfsh8="

ota:
  - platform: esphome
    password: "ae914fc7bfa12b4fd5a49395a6bfee56"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Kiosk-1 Fallback Hotspot"
    password: "z8VbVEO3CHSV"

captive_portal:

external_components:
  - source: github://pr#6209
    components: [ waveshare_epaper ]

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

font:
  - file: "gfonts://Inter@700"
    id: font_large
    size: 72
  - file: "gfonts://Inter@700"
    id: font_medium
    size: 48
  - file: "gfonts://Inter@700"
    id: font_small
    size: 24

time:
  - platform: homeassistant
    id: esptime

display:
  - platform: waveshare_epaper
    id: epaper_display
    cs_pin: GPIO5
    dc_pin: GPIO17
    busy_pin: GPIO4
    reset_pin: GPIO16
    model: 4.20in-v2
    full_update_every: 1
    update_interval: 60s
    display_mode: FULL
    
    lambda: |-
      it.fill(COLOR_OFF);
      it.print(200, 150, id(font_large), COLOR_ON, TextAlign::CENTER, "Hello World");
      
      if (id(esptime).now().is_valid()) {
        it.strftime(200, 20, id(font_small), COLOR_ON, TextAlign::TOP_CENTER, 
                    "%A %B %d, %Y", id(esptime).now());
        it.strftime(200, 50, id(font_medium), COLOR_ON, TextAlign::TOP_CENTER, 
                    "%I:%M %p", id(esptime).now());
      }
      
      it.rectangle(5, 5, 390, 290, COLOR_ON);
